title: "LA â€” Personal Blog: Time-Being"
email: ""
description: "Web-journal of Leigh-Ann (LA)"
baseurl: ""
url: "https://leighannjfenwick.github.io"
theme: minima
markdown: kramdown
author:
  name: "Leigh-Ann Fenwick"
paginate: 5
collections:
  books:
    output: true
plugins: []
